### ISSUE TITLE
Event edit approval notifications

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade-event-publish-trigger#2]
We need to change our emails so there is one that goes out on initial approval and one that goes out on edits. The edit email, however, will not be sent out when any ol' user edits or publishes the event page (ie, if a student makes a change or we do a site-wide publish).

Hannon Hill told @c-schwarze about a dirty way to code this.

**Comment by c-schwarze** [comment]
This is completed. 

We had to create a hidden metadata field 'tinker-edits' to all event pages. Tinker will set the value to 1, when an event is submitted through tinker. Then this publish trigger sends an email only if the value is set to 1. After the email is sent, the value is reset to 0, so no emails can be sent, unless the event is edited in Tinker again.

However, there might be a slight issue as this starts up, since some events already have the field set to 1, but they also have already received the email.
